spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode:never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  social-login:
    provider:
      apple:
        redirect-uri: https://ttakkeun.app.com/apple/callback/
        client-id: ${APPLE_CLIENT_ID}
        key-id: ${APPLE_KEY_ID}
        team-id: ${APPLE_TEAM_ID}
        audience: https://appleid.apple.com
        private-key: ${APPLE_SECRET}
      kakao:
        redirect-uri: http://ttakkeun.com:8080/oauth/kakao/callback
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      resolve-lazily: true
  jackson:
    time-zone: Asia/Seoul
jwt:
  secretKey: ${JWT_SECRET}

server:
  port: 8080

naverApi:
  clientId: ${NAVER_ClientID}
  clientSecret: ${NAVER_ClientSecret}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS}
      secret-key: ${AWS_SECRET}
    region:
      static: ap-northeast-2
      # 리전 서울로 설정
    s3:
      bucket: ttakkeun-bucket

openai:
  secret-key: ${OPENAI_KEY}
  url:
    model: "https://api.openai.com/v1/models"
    model-list: "https://api.openai.com/v1/models/"
    prompt: "https://api.openai.com/v1/chat/completions"

# application.yml
logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    ttakkeun.ttakkeun_server: TRACE
