-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPQGPRZ9oIGAb6vra
c5qBDEedIMdWGC5XoQ2vA9lEv9OgCgYIKoZIzj0DAQehRANCAAS/SY9RpfX94Ok3
ZyDGK0FLQbU/eM9k87x3FsD7evBxGLZuF+eyVFSJedGDq7jifLEQiaV0tRkhZdVo
F3CzBPNE
-----END PRIVATE KEY-----